// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewspaperServer.Models;

#nullable disable

namespace NewspaperServer.Migrations
{
    [DbContext(typeof(NewContext))]
    [Migration("20251126220328_RemoveNorthwind")]
    partial class RemoveNorthwind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewspaperServer.Models.Address1", b =>
                {
                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("city");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int")
                        .HasColumnName("house_number");

                    b.Property<string>("Street")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("street");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int")
                        .HasColumnName("zip_code");

                    b.HasKey("AddressId")
                        .HasName("PK__address1__CAA247C8BC71EC90");

                    b.ToTable("address1", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.NewsForPack", b =>
                {
                    b.Property<int>("NewsForPackId")
                        .HasColumnType("int")
                        .HasColumnName("news_for_pack_id");

                    b.Property<int>("NewsId")
                        .HasColumnType("int")
                        .HasColumnName("news_id");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.HasKey("NewsForPackId")
                        .HasName("PK__news_for__B8CB6B6E5B5582EF");

                    b.HasIndex("NewsId");

                    b.HasIndex("PackageId");

                    b.ToTable("news_for_pack", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.Newspaper", b =>
                {
                    b.Property<int>("NewsId")
                        .HasColumnType("int")
                        .HasColumnName("news_id");

                    b.Property<string>("TypeNews")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_news");

                    b.HasKey("NewsId")
                        .HasName("PK__newspape__4C27CCD82E9E50E6");

                    b.ToTable("newspaper", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.Packages1", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<int?>("NumNewspaper")
                        .HasColumnType("int")
                        .HasColumnName("num_newspaper");

                    b.Property<string>("NumSubscrition")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("num_subscrition");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("package_type");

                    b.Property<int?>("Payment")
                        .HasColumnType("int")
                        .HasColumnName("payment");

                    b.HasKey("PackageId")
                        .HasName("PK__packages__63846AE8F6247BC8");

                    b.ToTable("packages1", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.Section", b =>
                {
                    b.Property<int>("SectionsId")
                        .HasColumnType("int")
                        .HasColumnName("sections_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("NameSec")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("name_sec");

                    b.Property<int>("NewsId")
                        .HasColumnType("int")
                        .HasColumnName("news_id");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("worker_id");

                    b.HasKey("SectionsId")
                        .HasName("PK__sections__CE9F3A87E530728B");

                    b.HasIndex("NewsId");

                    b.HasIndex("WorkerId");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.Subscrition", b =>
                {
                    b.Property<int>("SubId")
                        .HasColumnType("int")
                        .HasColumnName("sub_id");

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<DateOnly?>("DateAdd")
                        .HasColumnType("date")
                        .HasColumnName("date_add");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number");

                    b.HasKey("SubId")
                        .HasName("PK__subscrit__694106B0F43D03FE");

                    b.HasIndex("AddressId");

                    b.HasIndex("PackageId");

                    b.ToTable("subscrition", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.TypeWorker", b =>
                {
                    b.Property<int>("TypeWorkerId")
                        .HasColumnType("int")
                        .HasColumnName("type_worker_id");

                    b.Property<string>("NameType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("name_type");

                    b.HasKey("TypeWorkerId")
                        .HasName("PK__type_wor__A6E0C52144704B1B");

                    b.ToTable("type_worker", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.Worker", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("worker_id");

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<int?>("NumForWeek")
                        .HasColumnType("int")
                        .HasColumnName("num_for_week");

                    b.Property<int?>("SalaryForHour")
                        .HasColumnType("int")
                        .HasColumnName("salary_for_hour");

                    b.Property<int>("TypeWorkerId")
                        .HasColumnType("int")
                        .HasColumnName("type_worker_id");

                    b.HasKey("WorkerId")
                        .HasName("PK__worker__569F8007D7AF20AA");

                    b.HasIndex("AddressId");

                    b.HasIndex("TypeWorkerId");

                    b.ToTable("worker", (string)null);
                });

            modelBuilder.Entity("NewspaperServer.Models.NewsForPack", b =>
                {
                    b.HasOne("NewspaperServer.Models.Newspaper", "News")
                        .WithMany("NewsForPacks")
                        .HasForeignKey("NewsId")
                        .IsRequired()
                        .HasConstraintName("FK_news_id");

                    b.HasOne("NewspaperServer.Models.Packages1", "Package")
                        .WithMany("NewsForPacks")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK_package_id");

                    b.Navigation("News");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("NewspaperServer.Models.Section", b =>
                {
                    b.HasOne("NewspaperServer.Models.Newspaper", "News")
                        .WithMany("Sections")
                        .HasForeignKey("NewsId")
                        .IsRequired()
                        .HasConstraintName("FK_news_id2");

                    b.HasOne("NewspaperServer.Models.Worker", "Worker")
                        .WithMany("Sections")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("FK_worker_id5");

                    b.Navigation("News");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("NewspaperServer.Models.Subscrition", b =>
                {
                    b.HasOne("NewspaperServer.Models.Address1", "Address")
                        .WithMany("Subscritions")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_address_id2");

                    b.HasOne("NewspaperServer.Models.Packages1", "Package")
                        .WithMany("Subscritions")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK_package_id2");

                    b.Navigation("Address");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("NewspaperServer.Models.Worker", b =>
                {
                    b.HasOne("NewspaperServer.Models.Address1", "Address")
                        .WithMany("Workers")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_address_id");

                    b.HasOne("NewspaperServer.Models.TypeWorker", "TypeWorker")
                        .WithMany("Workers")
                        .HasForeignKey("TypeWorkerId")
                        .IsRequired()
                        .HasConstraintName("FK_type_worker_id");

                    b.Navigation("Address");

                    b.Navigation("TypeWorker");
                });

            modelBuilder.Entity("NewspaperServer.Models.Address1", b =>
                {
                    b.Navigation("Subscritions");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("NewspaperServer.Models.Newspaper", b =>
                {
                    b.Navigation("NewsForPacks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("NewspaperServer.Models.Packages1", b =>
                {
                    b.Navigation("NewsForPacks");

                    b.Navigation("Subscritions");
                });

            modelBuilder.Entity("NewspaperServer.Models.TypeWorker", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("NewspaperServer.Models.Worker", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
